# === CONFIG FOR SmartDCA-Pro Bot ===

TRADING_PAIR = "SOLUSDT"

DCA_GAP_PERCENT = 8
TP_TRAIL_PERCENT = 10
TP_TRAIL_CALLBACK = 5
CAPITAL_PER_ENTRY = 100
MAX_DCA_ENTRIES = 3
MAX_TOTAL_DRAWDOWN = 30
RSI_BUY_LIMIT = 25

TELEGRAM_ENABLED = True
TELEGRAM_BOT_TOKEN = "your_bot_token_here"
TELEGRAM_CHAT_ID = "your_chat_id_here"

CHECK_INTERVAL = 60
